apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-cloud-exporter
  namespace: monitoring
  labels:
    app: confluent-cloud-exporter
spec:
  replicas: 1 # Run a single instance of the exporter
  selector:
    matchLabels:
      app: confluent-cloud-exporter # Must match the labels in the Pod template
  template:
    metadata:
      labels:
        app: confluent-cloud-exporter # Labels applied to the Pods
    spec:
      containers:
        - name: confluent-cloud-exporter
          image: cmatta/confluent-cloud-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9184 # Port the application listens on
              name: http-metrics
          env:
            # Load API Key and Secret from a Kubernetes Secret
            - name: CONFLUENT_EXPORTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-cloud-secrets # Name of your Secret
                  key: CONFLUENT_CLOUD_API_KEY                     # Key within the Secret for the API key
            - name: CONFLUENT_EXPORTER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: confluent-cloud-secrets # Name of your Secret
                  key: CONFLUENT_CLOUD_API_SECRET                  # Key within the Secret for the API secret
            # Enable debug logging
            - name: CONFLUENT_EXPORTER_LOG_LEVEL
              value: "debug"
            # Increase discovery interval to reduce API load
            - name: CONFLUENT_EXPORTER_DISCOVERY_INTERVAL
              value: "15m"
            # Increase metrics cache duration
            - name: CONFLUENT_EXPORTER_METRICS_CACHE_DURATION
              value: "5m"
          # --- Optional: Mount config.yaml from a ConfigMap ---
          # args:
          #   - "-config.file=/config/config.yaml"
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /config
          #     readOnly: true
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"  # 1 full CPU core
              memory: "2Gi" # 2GB of memory
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9184
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9184
            initialDelaySeconds: 5
            periodSeconds: 10
      # --- Optional: Define the volume if mounting config.yaml ---
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: confluent-exporter-config # Name of your ConfigMap